<a href="https://colab.research.google.com/github/jw13k/2024-1-my-DL/blob/main/inclass/0313_w01_deep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32, shape=[3])

#constant([5, 5, 5], tf.float32)
b = tf.Variable(3)

#a + b
c = tf.add(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(c, {a: [1, 2, 3]}))

[4 5 6]


In [31]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

c = tf.add(a,b)
d = tf.subtract(a,b)
e = tf.multiply(a,b)
f = tf.div(x,y)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print("Plus => " , sess.run(c, {a: [[1,2,3], [1,2,3]], b: [[3,2,3], [6,2,3]]}))
  print("Minus => " , sess.run(d, {a: [[1,2,3], [1,2,3]], b: [[3,2,3], [6,2,3]]}))
  print("Multiply => " , sess.run(e, {a: [[1,2,3], [1,2,3]], b: [[3,2,3], [6,2,3]]}))
  print("Div => " , sess.run(f, {x: [[1,2,3], [1,2,3]], y: [[3,2,3], [6,2,3]]}))

Plus =>  [[4 4 6]
 [7 4 6]]
Minus =>  [[-2  0  0]
 [-5  0  0]]
Multiply =>  [[3 4 9]
 [6 4 9]]
Div =>  [[0.33333334 1.         1.        ]
 [0.16666667 1.         1.        ]]


In [33]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

c = tf.add(a,b)
d = tf.subtract(a,b)
e = tf.multiply(a,b)
f = tf.div(x,y)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print("Plus => " , sess.run(c, {a: [[1,2,3], [1,2,3]], b: [[3,2,3], [6,2,3]]}))
  print("Minus => " , sess.run(d, {a: [[1,2,3], [1,2,3]], b: [[3,2,3], [6,2,3]]}))
  print("Multiply => " , sess.run(e, {a: [[1,2,3], [1,2,3]], b: [[3,2,3], [6,2,3]]}))
  print("Div => " , sess.run(f, {x: [[1,2,3], [1,2,3]], y: [[3,2,3], [6,2,3]]}))

Plus =>  [[4 4 6]
 [7 4 6]]
Minus =>  [[-2  0  0]
 [-5  0  0]]
Multiply =>  [[3 4 9]
 [6 4 9]]
Div =>  [[0.33333334 1.         1.        ]
 [0.16666667 1.         1.        ]]
